from __future__ import annotations

from crawler.discovery_filters import (
    DISCOVERY_BLOCKED_FILE_EXTENSIONS as DISCOVERY_BLOCKED_FILE_EXTENSIONS,
)
from crawler.discovery_filters import (
    DISCOVERY_BLOCKED_SCHEMES as DISCOVERY_BLOCKED_SCHEMES,
)

DISCOVERY_BLOCKED_HOST_EXACT = {
    "g",
    "localhost",
}

DISCOVERY_BLOCKED_HOST_SUFFIXES = (
    ".local",
    ".localhost",
    ".internal",
    ".invalid",
    ".test",
    ".example",
)

DISCOVERY_MAX_DEFAULT_PAGES = 900
DISCOVERY_MAX_DEFAULT_DEPTH = 5
DISCOVERY_MAX_LINKS_PER_PAGE = 2500
DISCOVERY_MAX_ACCEPTED_MULTIPLIER = 30

DISCOVERY_QUALITY_EXTRA_SCAN_PAGES = 250
DISCOVERY_MIN_GOOD_SCORE = 95
DISCOVERY_MAX_NO_NEW_GOOD = 120
